services:
  db:
    image: postgres
    container_name: postgres_db
    restart: no
    environment:
      POSTGRES_DB: drive_database
      POSTGRES_USER: drive_user
      POSTGRES_PASSWORD: drive_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper    
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  web:
    image: drive
    build: .  
    container_name: django-app
    restart: "no"
    depends_on:
      - db
      - kafka
      - minio
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      SECRET_KEY: "m(qeg#+@g5qmm3)!=x(xb_v6h8+z@kd6ed1e8xni&k7c7$zku8"
      DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost"
      DATABASE_NAME: "drive_database"
      DATABASE_USER: "drive_user"
      DATABASE_PASSWORD: "drive_password"
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
volumes:
  postgres_data:
  minio_data:

